var searchData=
[
  ['de_20colisión_203d_0',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20mapa_20cúbico_1',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20material_2',['Archivo de descripción de  material.',['../_material_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20material_20revisión_200_3',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['de_20descripción_20de_20material_20revisión_201_4',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['de_20descripción_20de_20modelos_203d_5',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20recursos_6',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['de_20descripción_20de_20un_20mapa_20de_20iluminación_20especular_7',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20un_20mapa_20de_20irradiancia_8',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20una_20fuente_20de_20texto_9',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20una_20textura_202d_10',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['de_20descripción_20de_20volumen_20de_20colisión_203d_11',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['de_20iluminación_20especular_12',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20irradiancia_13',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20mapa_20cúbico_14',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['de_20material_15',['Archivo de descripción de  material.',['../_material_file.html',1,'jsonfiles']]],
  ['de_20material_20revisión_200_16',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['de_20material_20revisión_201_17',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['de_20modelos_203d_18',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['de_20recursos_19',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['de_20texto_20',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20un_20mapa_20de_20iluminación_20especular_21',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['de_20un_20mapa_20de_20irradiancia_22',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['de_20una_20fuente_20de_20texto_23',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['de_20una_20textura_202d_24',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['de_20volumen_20de_20colisión_203d_25',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]],
  ['descripción_20de_20mapa_20cúbico_26',['Archivo de descripción de mapa cúbico.',['../_cubemap_file.html',1,'jsonfiles']]],
  ['descripción_20de_20material_27',['Archivo de descripción de  material.',['../_material_file.html',1,'jsonfiles']]],
  ['descripción_20de_20material_20revisión_200_28',['Archivo de descripción de material (revisión 0).',['../_material_file_v0.html',1,'MaterialFile']]],
  ['descripción_20de_20material_20revisión_201_29',['Archivo de descripción de material (revisión 1).',['../_material_file_v1.html',1,'MaterialFile']]],
  ['descripción_20de_20modelos_203d_30',['Archivo de descripción de modelos 3D.',['../_model3_d_file.html',1,'jsonfiles']]],
  ['descripción_20de_20recursos_31',['Archivos de descripción de recursos.',['../jsonfiles.html',1,'']]],
  ['descripción_20de_20un_20mapa_20de_20iluminación_20especular_32',['Archivo de descripción de un mapa de iluminación especular.',['../_specular_map_file.html',1,'jsonfiles']]],
  ['descripción_20de_20un_20mapa_20de_20irradiancia_33',['Archivo de descripción de un mapa de irradiancia.',['../_irradiance_map_file.html',1,'jsonfiles']]],
  ['descripción_20de_20una_20fuente_20de_20texto_34',['Archivo de descripción de una fuente de texto.',['../_font_file.html',1,'jsonfiles']]],
  ['descripción_20de_20una_20textura_202d_35',['Archivo de descripción de una textura 2D.',['../_texture_file.html',1,'jsonfiles']]],
  ['descripción_20de_20volumen_20de_20colisión_203d_36',['Archivo de descripción de volumen de colisión 3D.',['../_pre_built_collider3_d_file.html',1,'jsonfiles']]]
];
